SE-36-add-additional-units-to-concrete-input-conversions
leviat-tech/concrete pull request #111
Opened 2022-11-24 16:44 UTC by reeves999999

Added more unit types

2022-11-24 18:51 UTC, YT8434 commented on src/utils/units.js
> +  MNm: "MNm",
Is SI unit for stress not N/m²?

2022-11-25 09:39 UTC, YT8434 commented on src/utils/units.js
> +  MPa: 'N/m',
N/m² instead of N/m for stress unit

2022-11-25 09:47 UTC, YT8434 commented on src/utils/units.js
>    MPa: 'N/m',
MPa: 'N/m²'

2022-11-25 09:47 UTC, danielstorey requested changes

2022-11-25 09:47 UTC, danielstorey commented on src/utils/units.js
> +  MPa: 'N/m',
```suggestion
  MPa: 'N/m²',
```

2022-11-25 09:49 UTC, reeves999999 commented on src/utils/units.js
>    MPa: 'N/m',
Please check latest.

2022-11-25 09:49 UTC, reeves999999 commented on src/utils/units.js
> +  MPa: 'N/m',
Please check latest.

2022-11-25 09:49 UTC, reeves999999 commented on src/utils/units.js
> +  MNm: "MNm",
Please check latest.

2022-11-25 09:54 UTC, YT8434 approved these changes

2022-11-25 10:12 UTC, danielstorey approved these changes

2022-11-25 10:13 UTC, merged