Tscsc 601 UI fixes
leviat-tech/concrete pull request #132
Opened 2023-03-30 10:36 UTC by reeves999999

To better support a reported troublesome resolution of 1366px several elements have been revised. In general, the layout has been largely improved.

Files changed, any why:

**Checkbox.vue & RadioGroup.vue** - these now accept a "reverseLabelOrder" prop that places the control input before the label, rather than after it. If the prop is omitted, the layout should render as before. 

**Table.vue** - this now accepts a "tableClass" prop allowing arbitrary classes to be passed in. For column shoes > loads, this solves the issue whereby the table is far too narrow to show its content. Scrollbars and overflow in general have been addressed also.

**FormSection.vue && FormElement.vue** - general styling improvements such as removing the grey background. Screen real estate is now much improved.

Here is the new layout
![1](https://user-images.githubusercontent.com/55240533/228809212-76b38b96-a5ea-4edb-822b-86aa2c79d2f0.png)

2023-03-31 08:43 UTC, kwasilonek approved these changes

2023-03-31 16:37 UTC, danielstorey requested changes

2023-03-31 16:37 UTC, danielstorey commented on src/components/FormElement/FormElement.vue
> +  props.labelOrder && `order-${props.labelOrder} !basis-auto`;
String concatenation doesn't work great with Tailwind classes
https://tailwindcss.com/docs/content-configuration#dynamic-class-names

2023-03-31 16:37 UTC, danielstorey commented on src/components/RadioGroup/RadioGroup.vue
> +  reverseLabelOrder: { type: Boolean, default: false },
Again, maybe a class that's easier to use with kebab case might be more appropriate?
`<RadioGroup reverse-labels />`

2023-04-03 09:21 UTC, danielstorey approved these changes

2023-04-03 09:26 UTC, merged