Se 44 add transition to listbox
leviat-tech/concrete pull request #151
Opened 2023-05-16 10:53 UTC by reeves999999

Added transition effects to Autocomplete (contains Combobox) and Listbox. Note that the Accordion control has been revised to accept an overflowing object (the Listbox) and as such now toggles its own overflow state.

2023-05-16 12:44 UTC, danielstorey requested changes

2023-05-16 12:44 UTC, danielstorey commented on src/components/Accordion/Accordion.vue
> +    setTimeout(() => (styles.overflow = 'visible'), TRANSITION_TIME);
we need to revert to using height: auto. Otherwise if the screen is resized and the content height changes the container will be stuck at the previous fixed height

2023-05-16 14:37 UTC, reeves999999 commented on src/components/Accordion/Accordion.vue
> +    setTimeout(() => (styles.overflow = 'visible'), TRANSITION_TIME);
Added auto back in.

2023-05-16 15:08 UTC, danielstorey approved these changes
minor formatting issues

2023-05-16 15:08 UTC, danielstorey commented on src/components/Accordion/Accordion.vue
> +let styles = reactive({ height: initialHeight, overflow: initialOverflow });
let -> const and consider multilining for readability

2023-05-16 15:08 UTC, danielstorey commented on src/components/Accordion/Accordion.vue
> +    setTimeout(() => (styles.overflow = 'visible',styles.height='auto'), TRANSITION_TIME);
can you use multilines for multiple statements/expressions? Inconsistent spacing too.

2023-05-16 15:08 UTC, danielstorey commented on src/components/Accordion/Accordion.vue
> +    styles.height='0';
inconsistent spacing

2023-05-18 12:22 UTC, reeves999999 commented on src/components/Accordion/Accordion.vue
> +let styles = reactive({ height: initialHeight, overflow: initialOverflow });
Revised as suggested

2023-05-18 14:19 UTC, danielstorey approved these changes

2023-05-22 08:14 UTC, kwasilonek approved these changes

2023-05-22 08:22 UTC, merged