feat: add info option to form elements
leviat-tech/concrete pull request #183
Opened 2023-05-24 11:20 UTC by mattbarton44

2023-05-24 12:19 UTC, danielstorey requested changes
Love the idea but think it could be improved a bit as per comments

2023-05-24 12:19 UTC, danielstorey commented on src/components/FormElement/FormElement.vue
> +        </div>
I'd prefer to avoid repetition here. And also this is likely something we would want to use elsewhere as well. So could we:
- Create a `v-tooltip` directive that for now just adds the title attribute but that we can extend in future to customise to appearance and behaviour of tooltips
- Create a `CTooltipIcon` component which renders the info icon with a `v-tooltip` attribute
- Consider using flex reverse classes to modify the order of appearance instead of repeating multiple lines of code for before/after positioning
- Bit picky but rename 'info' to 'tooltip' to adhere to industry-wide terminology

2023-05-25 11:32 UTC, danielstorey commented on src/directives/tooltip.js
> +  console.log(binding)
remove these :)

2023-05-25 11:32 UTC, danielstorey approved these changes

2023-05-25 13:34 UTC, kwasilonek approved these changes

2023-05-26 12:13 UTC, merged