feat: add imperial units for inch and feet
leviat-tech/concrete pull request #237
Opened 2023-11-14 13:10 UTC by reeves999999

Add inch and feet conversions

2023-11-14 14:26 UTC, YT8434 commented on src/utils/units.js
> +    ft: (ft) => ft.div(3.280839895),
not approximately but exactly:
```
m: {
 in: (inch) => inch.times(0.0254),
 ft: (ft) => ft.times(0.3048),
}
```
```
 in: {
    m: (inch) => inch.div(0.0254),
  },
  ft: {
    m: (ft) => ft.div(0.3048),
  },
};
```

2023-11-14 15:02 UTC, reeves999999 commented on src/utils/units.js
> +    ft: (ft) => ft.div(3.280839895),
Applied suggestion

2023-11-14 15:59 UTC, YT8434 commented on src/utils/units.js
> +  kip:'kN'
should to SI unit:
`lbf:'N',
  lbfin:'Nm',
  kip:'N'`

2023-11-15 08:21 UTC, YT8434 approved these changes

2023-11-15 09:56 UTC, danielstorey requested changes

2023-11-15 09:56 UTC, danielstorey commented on src/utils/units.js
> +    lbf: (lbf) => lbf.time(0.0044482216152605),
```suggestion
    lbf: (lbf) => lbf.times(0.0044482216152605),
```

2023-11-16 09:23 UTC, kwasilonek approved these changes

2023-11-16 12:07 UTC, danielstorey commented on src/components/NumericInput/NumericInput.vue
> +  if(numericInputPrecision) return parseFloat(value.toFixed(numericInputPrecision), 10);
```suggestion
const precision = props.precision ?? unitPrecision;
return precision ? parseFloat(value.toFixed(precision ), 10) : value;
```

2023-11-16 12:39 UTC, reeves999999 commented on src/components/NumericInput/NumericInput.vue
> +  if(numericInputPrecision) return parseFloat(value.toFixed(numericInputPrecision), 10);
Suggestion applied, ta.

2023-11-16 12:57 UTC, danielstorey approved these changes

2023-11-16 12:59 UTC, merged