feat: Add TextArea component
leviat-tech/concrete pull request #68
Opened 2022-08-15 11:09 UTC by robiharid

![image](https://user-images.githubusercontent.com/16907484/184625046-0a7cbb46-0176-4bc1-834d-54c214a0125f.png)

2022-08-15 13:52 UTC, mattbarton44 requested changes

2022-08-15 13:52 UTC, mattbarton44 commented on src/components/TextArea/TextArea.vue
> +    v-bind="{ id, label, size, color, labelFormatter, message }"
Need to pass stacked in too for FormElement
```suggestion
    v-bind="{ id, label, size, color, labelFormatter, message, stacked }"
```

2022-08-15 13:52 UTC, mattbarton44 commented on src/components/TextArea/TextArea.vue
> +import { useSizeValue } from '../../composables/forms';
forms contain UseStackedValue and useFormElementValue which can both be used the same way as useSizeValue to be bound to formElement

2022-08-15 13:52 UTC, mattbarton44 commented on src/components/TextArea/TextArea.vue
> +const formElement = props.isFormElement || !!props.label;
```suggestion
const formElement = useFormElementValue(props.label);
```

2022-08-15 14:17 UTC, robiharid commented
Brill, thanks @mattbarton44 for clearing up the use case for the composable useFormElementValue. 
All suggestions are reflected for you now. :)

2022-08-15 14:19 UTC, danielstorey approved these changes

2022-08-15 15:36 UTC, mattbarton44 requested changes

2022-08-15 15:36 UTC, mattbarton44 commented on src/components/TextArea/TextArea.vue
> +import { useFormElementValue } from '../../composables/forms';
```suggestion
import { useSizeValue, useStackedValue, useFormElementValue } from '../../composables/forms';
```

2022-08-15 15:36 UTC, mattbarton44 commented on src/components/TextArea/TextArea.vue
> +const formElement = useFormElementValue(props.label);
```suggestion
const stacked = useStackedValue(props.stacked);
const formElement = useFormElementValue(props.label);
```

2022-08-15 15:36 UTC, mattbarton44 commented on src/components/TextArea/TextArea.vue
> +const size = useFormElementValue(props.size);
```suggestion
const size = useSizeValue(props.size);
```

2022-08-16 12:28 UTC, mattbarton44 approved these changes

2022-08-16 12:29 UTC, merged