V2 feature/tabs
leviat-tech/concrete pull request #74
Opened 2022-08-17 22:15 UTC by robiharid

To-do:

- Storybook documentation example usage with template labels
- Equal height on CTabPanel content -> use grid-template-rows to fix height of content? As content is passed as template, it will be easier to fix height of content using parent, i.e. grid styles
- Possible transition(?)

![image](https://user-images.githubusercontent.com/16907484/185252641-76a5b459-a7ec-4d3f-b27e-cddd770b50b1.png)

2022-08-18 11:20 UTC, mattbarton44 approved these changes

2022-08-18 13:47 UTC, danielstorey approved these changes
Just a couple of comments. Also you need to add the imports and exports to index.js :)

2022-08-18 13:47 UTC, danielstorey commented on src/components/Tabs/CTabLabel.vue
> +</style>
I'd prefer that we follow the headless ui guidelines for styling tabs
https://headlessui.com/vue/tabs#styling-the-selected-tab

2022-08-18 13:47 UTC, danielstorey commented on src/components/Tabs/CTabList.vue
> +  labels: { type: Array, default: () => [] },
really minor but this can be simplified as we don't really need a function to return an empty array. And since we don't need to cast the prop for any other logic we could just have `labels: Array`

2022-08-18 13:47 UTC, danielstorey commented on src/components/Tabs/Tabs.vue
> +  <div class="border">
Can you remove this wrapper. We'll possibly only want a l or r border but this may change project to project so we need the flexibility

2022-08-18 13:48 UTC, danielstorey requested changes
Please make the changes as per previous comments

2022-08-19 09:34 UTC, robiharid commented on src/components/Tabs/CTabLabel.vue
> +</style>
Brill, thanks for bringing this up - my only concern was that by using scss we could target slot labels that did not exist in the child component. This would mean that labels provided via slot would have to have their active state style manually as well. 

However, as long as we try to restrict slot usage to <CTabLabel> then using the headless way seems cleaner :)

2022-08-19 09:35 UTC, robiharid commented
@danielstorey Thanks again for digging deep on this one! Good food for thought :)

2022-08-19 15:30 UTC, danielstorey approved these changes

2022-08-19 15:46 UTC, CalumH0 approved these changes

2022-08-19 15:55 UTC, merged