Se 31 make modal accessible and enable keyboard events
leviat-tech/concrete pull request #99
Opened 2022-10-14 10:34 UTC by robiharid

- SE-31 Make modal accessible and enable keyboard events
- SE-33 CModal - content not visible if it exceeds the height of the page

![image](https://user-images.githubusercontent.com/16907484/195826389-a98d9e28-00db-4c7f-8fe3-003a0bb6e494.png)

Was slightly tricky trying to create focusTrap within modal - without the use of plugins, vue directives, composables etc. Focus handler method is simple and prevents focus (key board tabbing) leaving the modal element (otherwise it would tab through forms etc in the background)

2022-10-14 10:54 UTC, danielstorey requested changes
Couple of minor comments. The main thing that needs changing is the aria attribute typo

2022-10-14 10:54 UTC, danielstorey commented on src/components/Modal/Modal.vue
> +      @click.self="onClose" @keydown.esc="onClose" ref="modal" aria-model="true" role="dialog">
should this be `aria-modal`?
```suggestion
      @click.self="onClose" @keydown.esc="onClose" ref="modal" aria-modal="true" role="dialog">
```

2022-10-14 10:54 UTC, danielstorey commented on src/components/Modal/Modal.vue
> +});
`watch` might be a bit cleaner. `onUpdated` is a bit generic

```suggestion
watch(() => props.show, (showValue) => {
  if (showValue) {
    focusModal();
  }
});
```

2022-10-14 10:54 UTC, danielstorey commented on src/components/Modal/Modal.vue
> +          <button v-if="closeable" class="p-4 mr-2" @click="onClose" tabindex="0" @focus="focusModal">
is the tabindex attribute needed? I thought buttons were automatically tab-enabled

2022-10-14 13:28 UTC, robiharid commented on src/components/Modal/Modal.vue
> +});
onUpdated was used because it is called after the DOM has finished updating.
I refactored the watch to use nextTick so we can ensure the Modal element is always present in the DOM

2022-10-14 14:45 UTC, danielstorey commented on src/components/Modal/Modal.vue
> +    });
```suggestion
    nextTick(focusModal);
```
;)

2022-10-14 14:50 UTC, robiharid commented on src/components/Modal/Modal.vue
> +    });
Haha, keen eye! 
I personally prefer keeping callbacks in the IIFE format, for the same reason I prefer returning {} in arrow functions - to make it easier to debug and log things quicker

2022-10-19 10:48 UTC, CalumH0 approved these changes

2022-10-19 11:49 UTC, merged